### ISSUE TITLE
Docker container keeps crashing and I can't work out why

### ISSUE THREAD

**Issue by Deanosim** [Place1/wg-access-server#61]
The error message I'm getting any time I try and launch the container

```
time="2020-07-17T14:15:28Z" level=info msg="starting wireguard server on 0.0.0.0:51820" file="main.go:50"
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa34921]

goroutine 1 [running]:
github.com/place1/wg-embed/pkg/wgembed.(*ConfigFile).Config(...)
/go/pkg/mod/github.com/place1/wg-embed@v0.1.0/pkg/wgembed/config.go:152
github.com/place1/wg-embed/pkg/wgembed.(*WireGuardInterface).LoadConfig(0xc000260510, 0xc0001e83c0, 0x4, 0xc000036090)
/go/pkg/mod/github.com/place1/wg-embed@v0.1.0/pkg/wgembed/iface.go:92 +0xd1
main.main()
/code/main.go:52 +0x229
```

**Comment by Place1** [comment]
@Deanosim would you be able to share the config you're passing to wg-access-server to help be debug this?

**Comment by Deanosim** [comment]
@Place1 Thanks for the reply, it would seem 0.2.4 fixed my problem with it's better error reporting. Turns out their was a problem with my private key, but I've fixed that now.

**Comment by Place1** [comment]
@Deanosim good to hear. I'll close this issue.
